### ISSUE TITLE
Please sort Expedition Events by name

### ISSUE THREAD

**Issue by corgatag** [Miraak7000/AssetViewer#24]
Hi,

Could you sort Expedition Events by name?  I tried to create a small feature branch with this 2-line change, but got a 403.

ExpeditionEvents.xaml.cs line 31

`          var document = XDocument.Parse(reader.ReadToEnd()).Root;`
`          var items = document.Elements().Select(s => s.FromXElement<ExpeditionEvent>()).OrderBy(item => item.Name.CurrentLang);`
`          foreach (var item in items) {`
`            Events.Add(item);`
`          }`

Thanks!

[ExpeditionEvents.xaml.cs.txt](https://github.com/Miraak7000/AssetViewer/files/4396873/ExpeditionEvents.xaml.cs.txt)

**Comment by Veraatversus** [comment]
The expedition events has to be reworked anyway. There are not all posible ways for the id's listed. Your solution isn't really good because the different possible languages. It would only be sorted by start language. I have planed to rework this soon and I will implement a feature like this. Thanks for report.

**Comment by Veraatversus** [comment]
plan has changed. its implemented in a similar way until the rework. does not resort after language changed. it will be in the next release with update 7 or now under https://drive.google.com/open?id=1N5AUPYDhhluKMLPEMvF45qsUs27ed6Cg
